export enum FoodCategory {
  MEAT = "MEAT",
  FISH = "FISH",
  VEGETABLE = "VEGETABLE",
  FRUIT = "FRUIT",
  DAIRY = "DAIRY",
  GRAIN = "GRAIN",
  SEASONING = "SEASONING",
  NOODLE = "NOODLE",
  SIDE = "SIDE",
  SEAFOOD = "SEAFOOD",
  NUT = "NUT",
  BREAD = "BREAD",
  RICE_CAKE = "RICE_CAKE",
  SAUCE = "SAUCE",
  FROZEN = "FROZEN",
  DRINK = "DRINK",
  INSTANT = "INSTANT",
  OTHER = "OTHER",
}

export const FoodCategoryLabel: Record<FoodCategory, string> = {
  [FoodCategory.MEAT]: "육류",
  [FoodCategory.FISH]: "어류",
  [FoodCategory.VEGETABLE]: "채소",
  [FoodCategory.FRUIT]: "과일",
  [FoodCategory.DAIRY]: "유제품",
  [FoodCategory.GRAIN]: "곡물",
  [FoodCategory.SEASONING]: "조미료",
  [FoodCategory.NOODLE]: "면류",
  [FoodCategory.SIDE]: "반찬",
  [FoodCategory.SEAFOOD]: "해산물",
  [FoodCategory.NUT]: "견과류",
  [FoodCategory.BREAD]: "빵류",
  [FoodCategory.RICE_CAKE]: "떡류",
  [FoodCategory.SAUCE]: "소스",
  [FoodCategory.FROZEN]: "냉동식품",
  [FoodCategory.DRINK]: "음료",
  [FoodCategory.INSTANT]: "인스턴트",
  [FoodCategory.OTHER]: "기타",
};

export const FoodCategoryColor: Record<FoodCategory, string> = {
  [FoodCategory.MEAT]: "#FF6B6B",
  [FoodCategory.FISH]: "#4ECDC4",
  [FoodCategory.VEGETABLE]: "#45B7D1",
  [FoodCategory.FRUIT]: "#96CEB4",
  [FoodCategory.DAIRY]: "#FFEAA7",
  [FoodCategory.GRAIN]: "#DDA0DD",
  [FoodCategory.SEASONING]: "#98D8C8",
  [FoodCategory.NOODLE]: "#FFB347",
  [FoodCategory.SIDE]: "#87CEEB",
  [FoodCategory.SEAFOOD]: "#20B2AA",
  [FoodCategory.NUT]: "#D2B48C",
  [FoodCategory.BREAD]: "#F0E68C",
  [FoodCategory.RICE_CAKE]: "#FFA07A",
  [FoodCategory.SAUCE]: "#98FB98",
  [FoodCategory.FROZEN]: "#B0C4DE",
  [FoodCategory.DRINK]: "#FF69B4",
  [FoodCategory.INSTANT]: "#DDA0DD",
  [FoodCategory.OTHER]: "#F7DC6F",
};
