"""add weight and activityLevel to users

Revision ID: d648660b4f7b
Revises: a9ed9c4b8801
Create Date: 2025-11-21 15:01:24.694106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd648660b4f7b'
down_revision: Union[str, Sequence[str], None] = 'a9ed9c4b8801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('activityLevel', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activityLevel')
    op.drop_column('users', 'weight')
    # ### end Alembic commands ###
